baseURL = 'https://20SekK1.github.io/'
languageCode = 'ja'
title = '堰のページ'
theme = 'PaperMod'

# hugo.toml

[outputs]
  home = ["HTML","RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 11

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 12

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 13
    # サイトのトップレベル設定

# サイトのトップレベル設定    

  [params.homeInfoParams]
    Title = ""
    Content = '''
このサイトは個人の勉強ノートや記事を挙げていく予定であり,
所属先の公式の見解を代表するものではありません.
'''

# --- PaperModのパラメータ設定 ---
[params]
    # テーマ設定
    defaultTheme = "auto" # ページのテーマ設定 "dark", "light"も決められる
    disableThemeToggle = false # dark/light の変更ボタンを表示するかどうか

    # 記事表示に関する設定
    ShowReadingTime = true      # 各記事の読み終わるまでの時間を表記するかどうか
    ShowPostNavLinks = true     # 前後のポストへのNavigationを表示するかどうか
    ShowBreadCrumbs = true      # 各記事の階層関係を表示するかどうかうか
    ShowWordCount = true        # 各記事の文字数を表記するかどうか
    UseHugoToc = true # Hugoの組み込みTOC機能を使用するかどうか
    disableScrollToTop = true # 最上部へのスクロールボタンの表示の有無

# hugo.toml

  [markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
